import { Platform, Share } from "react-native";

export interface ExportOptions {
  format: "pdf" | "json" | "csv";
  includeMetadata: boolean;
  includeImages: boolean;
}

export interface ImpactCertificate {
  userId: string;
  userName: string;
  contributionType: string;
  points: number;
  date: string;
  certificateId: string;
}

// PDF Export Utilities
export async function generateImpactReportPDF(data: {
  title: string;
  metrics: Record<string, any>;
  stories: Array<{ icon: string; title: string; description: string }>;
  generatedDate: string;
}): Promise<string> {
  try {
    // This would use a PDF generation library like react-native-pdf or similar
    // For now, returning a placeholder that would be replaced with actual PDF generation
    const pdfContent = `
# ${data.title}

Generated: ${data.generatedDate}

## Global Impact Metrics

${Object.entries(data.metrics)
  .map(([key, value]) => `- ${key}: ${value}`)
  .join("\n")}

## Impact Stories

${data.stories.map((story) => `### ${story.icon} ${story.title}\n${story.description}`).join("\n\n")}

---
Generated by Guardian-IO
Transparent. Resilient. Regenerative.
    `;

    return pdfContent;
  } catch (error) {
    console.error("Failed to generate impact report PDF:", error);
    throw error;
  }
}

export async function generateContributionCertificatePDF(
  certificate: ImpactCertificate,
): Promise<string> {
  try {
    const pdfContent = `
╔════════════════════════════════════════════════════════════╗
║                                                            ║
║          🌍 GUARDIAN-IO CONTRIBUTION CERTIFICATE 🌍       ║
║                                                            ║
╚════════════════════════════════════════════════════════════╝

This Certificate is Proudly Presented to:

    ${certificate.userName}

For Outstanding Contribution to Global Impact

Contribution Type: ${certificate.contributionType}
Points Earned: ${certificate.points}
Date: ${certificate.date}
Certificate ID: ${certificate.certificateId}

By contributing to Guardian-IO, you have helped protect workers,
preserve biodiversity, and build a more equitable world.

Your actions matter. Your voice matters. Your impact matters.

═══════════════════════════════════════════════════════════════

Transparent. Resilient. Regenerative.
    `;

    return pdfContent;
  } catch (error) {
    console.error("Failed to generate contribution certificate:", error);
    throw error;
  }
}

// JSON Export
export function exportDataAsJSON(data: any, filename: string): string {
  try {
    const jsonString = JSON.stringify(data, null, 2);
    return jsonString;
  } catch (error) {
    console.error("Failed to export data as JSON:", error);
    throw error;
  }
}

// CSV Export
export function exportDataAsCSV(
  data: Array<Record<string, any>>,
  filename: string,
): string {
  try {
    if (data.length === 0) {
      return "";
    }

    const headers = Object.keys(data[0]);
    const csvContent = [
      headers.join(","),
      ...data.map((row) =>
        headers
          .map((header) => {
            const value = row[header];
            // Escape quotes and wrap in quotes if contains comma
            if (typeof value === "string" && (value.includes(",") || value.includes('"'))) {
              return `"${value.replace(/"/g, '""')}"`;
            }
            return value;
          })
          .join(","),
      ),
    ].join("\n");

    return csvContent;
  } catch (error) {
    console.error("Failed to export data as CSV:", error);
    throw error;
  }
}

// Social Media Sharing
export async function shareImpactStory(story: {
  title: string;
  description: string;
  metrics?: Record<string, string>;
  hashtags?: string[];
}): Promise<boolean> {
  try {
    const message = `
${story.title}

${story.description}

${story.metrics ? Object.entries(story.metrics).map(([k, v]) => `${k}: ${v}`).join("\n") : ""}

${story.hashtags ? story.hashtags.map((tag) => `#${tag}`).join(" ") : ""}

Join Guardian-IO and make a difference! 🌍
    `.trim();

    if (Platform.OS === "web") {
      // Web sharing
      const shareData = {
        title: story.title,
        text: message,
        url: "https://guardian-io.com",
      };

      if (navigator.share) {
        await navigator.share(shareData);
        return true;
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(message);
        return true;
      }
    } else {
      // Native sharing
      const result = await Share.share({
        message,
        title: story.title,
        url: "https://guardian-io.com",
      });

      return result.action !== Share.dismissedAction;
    }
  } catch (error) {
    console.error("Failed to share impact story:", error);
    return false;
  }
}

export async function shareContributionAchievement(achievement: {
  userName: string;
  achievementName: string;
  icon: string;
  points: number;
}): Promise<boolean> {
  try {
    const message = `
I just unlocked the "${achievement.achievementName}" ${achievement.icon} achievement on Guardian-IO!

Earned ${achievement.points} points for making a global impact.

Join me in protecting workers, preserving biodiversity, and building a better world.

#GuardianIO #ImpactMatters #GlobalChange
    `.trim();

    if (Platform.OS === "web") {
      if (navigator.share) {
        await navigator.share({
          title: "Guardian-IO Achievement",
          text: message,
          url: "https://guardian-io.com",
        });
        return true;
      } else {
        await navigator.clipboard.writeText(message);
        return true;
      }
    } else {
      const result = await Share.share({
        message,
        title: "Guardian-IO Achievement",
        url: "https://guardian-io.com",
      });

      return result.action !== Share.dismissedAction;
    }
  } catch (error) {
    console.error("Failed to share achievement:", error);
    return false;
  }
}

// Generate Shareable Link
export function generateShareableLink(
  type: "report" | "incident" | "achievement" | "profile",
  id: string,
): string {
  const baseUrl = "https://guardian-io.com";
  return `${baseUrl}/share/${type}/${id}`;
}

// Generate QR Code for sharing
export function generateQRCodeData(data: any): string {
  // This would generate QR code data that can be used with a QR code library
  const jsonString = JSON.stringify(data);
  const encodedData = encodeURIComponent(jsonString);
  return `https://guardian-io.com/qr?data=${encodedData}`;
}

// Download utilities
export async function downloadFile(content: string, filename: string, mimeType: string) {
  try {
    if (Platform.OS === "web") {
      const element = document.createElement("a");
      const file = new Blob([content], { type: mimeType });
      element.href = URL.createObjectURL(file);
      element.download = filename;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
      URL.revokeObjectURL(element.href);
    } else {
      // Native download would require additional permissions and libraries
      console.log(`Download requested: ${filename}`);
    }
  } catch (error) {
    console.error("Failed to download file:", error);
    throw error;
  }
}

// React Hook for data export
export function useDataExport() {
  const exportImpactReport = async (data: any) => {
    try {
      const pdf = await generateImpactReportPDF(data);
      await downloadFile(pdf, "impact-report.pdf", "application/pdf");
      return true;
    } catch (error) {
      console.error("Failed to export impact report:", error);
      return false;
    }
  };

  const exportContributionCertificate = async (certificate: ImpactCertificate) => {
    try {
      const pdf = await generateContributionCertificatePDF(certificate);
      await downloadFile(pdf, `certificate-${certificate.certificateId}.pdf`, "application/pdf");
      return true;
    } catch (error) {
      console.error("Failed to export certificate:", error);
      return false;
    }
  };

  const shareStory = async (story: any) => {
    return await shareImpactStory(story);
  };

  const shareAchievement = async (achievement: any) => {
    return await shareContributionAchievement(achievement);
  };

  return {
    exportImpactReport,
    exportContributionCertificate,
    shareStory,
    shareAchievement,
    generateShareableLink,
    generateQRCodeData,
  };
}
